spring:
  application:
    name: notifyah
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true  # 정적 리소스 매핑 활성화
  
  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/notifyah
    username: notifyah
    password: notifyah
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notifyah-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# WebSocket Configuration
websocket:
  endpoint: /ws
  allowed-origins: ${WEBSOCKET_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}

# JWT Configuration
jwt:
  secret: notifyah-secret-key-change-in-production
  expiration: 86400000 # 24 hours in milliseconds

# Server Configuration
server:
  port: ${SERVER_PORT:8080}


# Logging Configuration
logging:
  level:
    com.notifyah: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.web.socket: DEBUG 